name: google_geocoding
description: A new Flutter package for handle google geocoding api that geocoding and reverse geocoding requests are available
version: 0.2.0
homepage: https://github.com/bazrafkan/google_geocoding

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
